### ISSUE TITLE
Snitches sometimes fail to refresh

### ISSUE THREAD

**Issue by wingzero54** [CivMC/JukeAlert#21]
Reported by multiple players. 

Potential fix staged by #19

**Comment by Aleksey-Terzi** [comment]
The fix is here: https://github.com/CivMC/CivModCore/pull/78
Though #19 is also useful.

**Comment by wingzero54** [comment]
Thank you for the clarification

**Comment by wingzero54** [comment]
https://github.com/CivMC/CivModCore/pull/78
