### ISSUE TITLE
[Regression] /jainfo arguments don't work

### ISSUE THREAD

**Issue by awoo-civ** [CivMC/JukeAlert#23]
The following /jainfo arguments do not work:
 - "censor"
 - "action="
 - "player="
 - "next"

Attempting to use them, e.g. `/jainfo player=Raeders`, results in `player=Raeders is not a number`:

![2022-07-13 21-36 ](https://user-images.githubusercontent.com/17804892/178841463-fc5fcebf-ddba-42ba-b7e5-5700c72b5889.png)
![2022-07-13 21-36 _1](https://user-images.githubusercontent.com/17804892/178841464-ed8e8553-f532-451f-ae78-0614c98e5147.png)
![2022-07-13 21-36 _2](https://user-images.githubusercontent.com/17804892/178841465-805e938f-4a73-4ccb-9520-83aa95e0aa47.png)

Implementation is here: https://github.com/CivMC/JukeAlert/blob/master/paper/src/main/java/com/untamedears/jukealert/commands/InfoCommand.java#L38

**Comment by Aleksey-Terzi** [comment]
@awoo-civ 
What is **censor** and how it should work?

**Comment by awoo-civ** [comment]
@Aleksey-Terzi Looks like it censored locations in the logs:
 1. https://github.com/CivClassic/JukeAlert/blob/0d294b40f068e4a2b2e44cb4953e7f84346c3a76/src/main/java/com/untamedears/JukeAlert/commands/InfoCommand.java#L161
 2. https://github.com/CivClassic/JukeAlert/blob/0d294b40f068e4a2b2e44cb4953e7f84346c3a76/src/main/java/com/untamedears/JukeAlert/chat/SendSnitchInfo.java#L117
 3. https://github.com/CivClassic/JukeAlert/blob/0d294b40f068e4a2b2e44cb4953e7f84346c3a76/src/main/java/com/untamedears/JukeAlert/storage/JukeAlertLogger.java#L170

**Comment by Aleksey-Terzi** [comment]
I've changed how the filtering works.
Action type or player name maybe just part of the name, like you can enter **player=raed** and it will show all entries for player with the name that includes **raed** in its name
Options excluding page_number can be passed in any order.

The option **next** works as an independent option and doesn't require specifying the full filter.
I.e. if I will use **/jainfo next** it will use the previously entered filter.

Other details are described in the PR's description.
