### ISSUE TITLE
Snitch_refresh is not related to snitches

### ISSUE THREAD

**Issue by wingzero54** [CivMC/JukeAlert#3]

**Comment by Maxopoly** [comment]
Unclear what is the issue solely based on title, please describe more

**Comment by Diet-Cola** [comment]
@Maxopoly updated thoughts?

**Comment by Maxopoly** [comment]
https://github.com/CivMC/JukeAlert/blob/master/paper/src/main/java/com/untamedears/jukealert/database/JukeAlertDAO.java#L245 Seems fine and should already have been fine on civclassic.

**Comment by wingzero54** [comment]
May have been a random CivClassic issue, will re-create if it appears again on CivMC
